### ISSUE TITLE
Сборка, проект

### ISSUE THREAD

**Issue by vlavolk** [Khorrth/Carbon#1]
Сборка должна производится для директории с исходниками, а не для единого файла. Думаю стоит воспользоваться Eclipse Java Compiler, чтобы уйти от использования JDK (слишком большой вес). Неплохо будет, если появится удобное управление проектами, например отдельный каталог с проектами и команды для управления оными.

**Comment by Khorrth** [comment]
Thanx for Your feedback and advices. Please, use English to ease understanding for foreigners.
It seems like You speak about "master" branch of Carbon. It is really primitive and it is kept for history.
"Oxyde" branch is the development branch of the project and all the features will be implemented there.
I'll write the goals of the project to the "README" file and close this issue.
